-- Mod: prismatic_stone
-- Code generated by the Simple Minetest Mod Maker
--   ( https://rubenwardy.github.io/minetest_mod_maker )

minetest.register_node("prismatic_stone:pink_prismatic_stone", {
	description = "Pink prismatic stone",
	tiles = {
		"prismatic_stone_pink_prismatic_stone.png", -- top
		"prismatic_stone_pink_prismatic_stone.png", -- bottom
		"prismatic_stone_pink_prismatic_stone.png", -- right
		"prismatic_stone_pink_prismatic_stone.png", -- left
		"prismatic_stone_pink_prismatic_stone.png", -- back
		"prismatic_stone_pink_prismatic_stone.png"  -- front
	},
	groups = {cracky = 2}
})

minetest.register_node("prismatic_stone:cyan_prismatic_stone", {
	description = "Cyan prismatic stone",
	tiles = {
		"prismatic_stone_blue_prismatic_stone.png", -- top
		"prismatic_stone_blue_prismatic_stone.png", -- bottom
		"prismatic_stone_blue_prismatic_stone.png", -- right
		"prismatic_stone_blue_prismatic_stone.png", -- left
		"prismatic_stone_blue_prismatic_stone.png", -- back
		"prismatic_stone_blue_prismatic_stone.png"  -- front
	},
	groups = {cracky = 2}
})

minetest.register_node("prismatic_stone:green_prismatic_stone", {
	description = "Green prismatic stone",
	tiles = {
		"prismatic_stone_green_prismatic_stone.png", -- top
		"prismatic_stone_green_prismatic_stone.png", -- bottom
		"prismatic_stone_green_prismatic_stone.png", -- right
		"prismatic_stone_green_prismatic_stone.png", -- left
		"prismatic_stone_green_prismatic_stone.png", -- back
		"prismatic_stone_green_prismatic_stone.png"  -- front
	},
	groups = {cracky = 2}
})

minetest.register_craft({
	output = '"prismatic_stone:pink_prismatic_stone" 8',
	recipe = {
		{"default:cobble", "default:cobble", "default:cobble"},
		{"default:cobble", "prismatic_stone:pink_coral_dye", "default:cobble"},
		{"default:cobble", "default:cobble", "default:cobble"},
	}
})

minetest.register_craft({
	output = '"prismatic_stone:cyan_prismatic_stone" 8',
	recipe = {
		{"default:cobble", "default:cobble", "default:cobble"},
		{"default:cobble", "prismatic_stone:cyan_coral_dye", "default:cobble"},
		{"default:cobble", "default:cobble", "default:cobble"},
	}
})

minetest.register_craft({
	output = '"prismatic_stone:green_prismatic_stone" 8',
	recipe = {
		{"default:cobble", "default:cobble", "default:cobble"},
		{"default:cobble", "prismatic_stone:green_coral_dye", "default:cobble"},
		{"default:cobble", "default:cobble", "default:cobble"},
	}
})

minetest.register_craftitem("prismatic_stone:pink_coral_dye", {
	description = "Pink coral dye",
	inventory_image = "prismatic_stone_pink_coral_dye.png",
 
	on_drop = function(itemstack, dropper, pos)
		-- Prints a random number and removes one item from the stack
		itemstack:take_item()
		return itemstack
	end,
})

minetest.register_craftitem("prismatic_stone:cyan_coral_dye", {
	description = "Cyan coral dye",
	inventory_image = "prismatic_stone_blue_coral_dye.png",
 
	on_drop = function(itemstack, dropper, pos)
		-- Prints a random number and removes one item from the stack
		itemstack:take_item()
		return itemstack
	end,
})

minetest.register_craftitem("prismatic_stone:green_coral_dye", {
	description = "Green coral dye",
	inventory_image = "prismatic_stone_green_coral_dye.png",
 
	on_drop = function(itemstack, dropper, pos)
		-- Prints a random number and removes one item from the stack
		itemstack:take_item()
		return itemstack
	end,
})

minetest.register_craft({
	output = '"prismatic_stone:cyan_coral_dye" 9',
	recipe = {
		{"", "", ""},
		{"", "default:coral_cyan", ""},
		{"", "", ""},
	}
})

minetest.register_craft({
	output = '"prismatic_stone:green_coral_dye" 9',
	recipe = {
		{"", "", ""},
		{"", "default:coral_green", ""},
		{"", "", ""},
	}
})

minetest.register_craft({
	output = '"prismatic_stone:pink_coral_dye" 9',
	recipe = {
		{"", "", ""},
		{"", "default:coral_pink", ""},
		{"", "", ""},
	}
})